package dominio;
// Generated 14/04/2013 19:45:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer idAsistencia;
     private Empleado empleado;
     private String estado;
     private byte[] imagen;
     private Date fecha;
     private Date hora;

    public Asistencia() {
    }

	
    public Asistencia(String estado, byte[] imagen, Date fecha, Date hora) {
        this.estado = estado;
        this.imagen = imagen;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Asistencia(Empleado empleado, String estado, byte[] imagen, Date fecha, Date hora) {
       this.empleado = empleado;
       this.estado = estado;
       this.imagen = imagen;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdAsistencia() {
        return this.idAsistencia;
    }
    
    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


