package dominio;
// Generated 19/04/2013 09:18:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int legajo;
     private Empresa empresa;
     private String apellido;
     private String nombre;
     private Integer dni;
     private String direccion;
     private String localidad;
     private String clave;
     private Boolean administrador;
     private String telefono;
     private Set asistencias = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int legajo, String apellido, String nombre, String clave) {
        this.legajo = legajo;
        this.apellido = apellido;
        this.nombre = nombre;
        this.clave = clave;
    }
    public Empleado(int legajo, Empresa empresa, String apellido, String nombre, Integer dni, String direccion, String localidad, String clave, Boolean administrador, String telefono, Set asistencias) {
       this.legajo = legajo;
       this.empresa = empresa;
       this.apellido = apellido;
       this.nombre = nombre;
       this.dni = dni;
       this.direccion = direccion;
       this.localidad = localidad;
       this.clave = clave;
       this.administrador = administrador;
       this.telefono = telefono;
       this.asistencias = asistencias;
    }
   
    public int getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Boolean getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Boolean administrador) {
        this.administrador = administrador;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


