/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Camara.java
 *
 * Created on 11/06/2010, 11:53:04 PM
 */

package estudiandojmf;

/**
 *
 * @author Cmop
 */
import Util.DetalleReporte;
import Util.FechaUtil;
import Util.ReporteAsitenciaJRDataSource;
import Util.TablaUtil;

import dominio.Asistencia;
import dominio.Empleado;
import dominio.OrdenarAsistenciaPorId;
import dominio.dao.AsistenciaDao;
import dominio.dao.EmpleadoDao;
import dominio.dao.imp.AsistenciaDaoImp;
import dominio.dao.imp.EmpleadoDaoImp;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.Player;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;


public class Camara extends javax.swing.JFrame
{Set<Asistencia> conjunto;
    
    private Player p1;
    private DefaultTableModel modelo;
    /** Creates new form Camara */
    public Camara(){
        initComponents();
        initComponents2();
 
    }

    public Player getPlayer()
    {
        return p1;
    }
    public void setPlayer(Player pin)
    {
        p1=pin;
    }
    public JPanel getCamara()
    {
        return panelCam;
    }

    private void initComponents2()
    {
        //registramos los Oyentes de eventos
        eventos e=new eventos(this);
        addWindowListener(e);
        jmCArchivo.addActionListener(e);
        jmCBD.addActionListener(e);
        jmSalir.addActionListener(e);
        jmAcerca.addActionListener(e);
        //Cargamos en el menu los Dispositivos detectados
        jDispositivos.menuDispositivos(this,jmDispositivos);
        setLocationRelativeTo(this); //centramos el formulario
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRectTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelRectTranslucidoComplete();
        clockDigital2 = new org.edisoncor.gui.varios.ClockDigital();
        clockFace2 = new org.edisoncor.gui.varios.ClockFace();
        txtLegajo = new org.edisoncor.gui.textField.TextFieldRectIcon();
        txtClave = new org.edisoncor.gui.passwordField.PasswordFieldRectIcon();
        btnMarcar = new org.edisoncor.gui.button.ButtonCircle();
        cmbElegir = new org.edisoncor.gui.comboBox.ComboBoxRound();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelCam = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();
        lblEmpleado = new javax.swing.JLabel();
        lbllFotoUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCapturar = new javax.swing.JMenu();
        jmCArchivo = new javax.swing.JMenuItem();
        jmCBD = new javax.swing.JMenuItem();
        jmDispositivos = new javax.swing.JMenu();
        jmOtros = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toma una Foto");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        panelRectTranslucidoComplete1.setColorDeSegundoBorde(new java.awt.Color(173, 173, 173));
        panelRectTranslucidoComplete1.setColorPrimario(new java.awt.Color(102, 102, 0));
        panelRectTranslucidoComplete1.setColorSecundario(new java.awt.Color(51, 0, 153));
        panelRectTranslucidoComplete1.setOpaque(false);

        clockDigital2.setBackground(new java.awt.Color(255, 255, 255));
        clockDigital2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18));

        javax.swing.GroupLayout clockFace2Layout = new javax.swing.GroupLayout(clockFace2);
        clockFace2.setLayout(clockFace2Layout);
        clockFace2Layout.setHorizontalGroup(
            clockFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        clockFace2Layout.setVerticalGroup(
            clockFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        txtLegajo.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtLegajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/user_16.png"))); // NOI18N
        txtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoActionPerformed(evt);
            }
        });

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 18));
        txtClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/iconKey2.jpg"))); // NOI18N

        btnMarcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/user_16.png"))); // NOI18N
        btnMarcar.setText("Ingresar");
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });

        cmbElegir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir", "Entrada", "Salida", " " }));
        cmbElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElegirActionPerformed(evt);
            }
        });

        labelCustom1.setBackground(new java.awt.Color(255, 255, 0));
        labelCustom1.setForeground(new java.awt.Color(0, 0, 0));
        labelCustom1.setText("Martes 12, de Marzo de 2013");
        labelCustom1.setBorde(true);
        labelCustom1.setColorDeSombra(new java.awt.Color(204, 204, 0));
        labelCustom1.setForma(org.edisoncor.gui.label.LabelCustom.Forma.BOTTOM);

        jLabel1.setText("LEGAJO");

        jLabel2.setText("CLAVE");

        javax.swing.GroupLayout panelRectTranslucidoComplete1Layout = new javax.swing.GroupLayout(panelRectTranslucidoComplete1);
        panelRectTranslucidoComplete1.setLayout(panelRectTranslucidoComplete1Layout);
        panelRectTranslucidoComplete1Layout.setHorizontalGroup(
            panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                        .addComponent(labelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(clockDigital2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucidoComplete1Layout.createSequentialGroup()
                                .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(cmbElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(clockFace2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucidoComplete1Layout.createSequentialGroup()
                        .addComponent(btnMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        panelRectTranslucidoComplete1Layout.setVerticalGroup(
            panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucidoComplete1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockDigital2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockFace2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(cmbElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panelImage1.setBorder(new javax.swing.border.MatteBorder(null));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoAzul4.jpg"))); // NOI18N

        panelCam.setBackground(new java.awt.Color(0, 0, 0));
        panelCam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camara", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        panelCam.setLayout(new java.awt.BorderLayout());

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Empleado", "Entrada/Salida", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAsistencia);

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));

        lbllFotoUser.setText("Aqui se mostrara su FOTO");
        lbllFotoUser.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setText("ireport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(lbllFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCam, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbllFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        jmCapturar.setText("Capturar");

        jmCArchivo.setText("En Archivo");
        jmCArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCArchivoActionPerformed(evt);
            }
        });
        jmCapturar.add(jmCArchivo);

        jmCBD.setText("En Base de Datos");
        jmCBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCBDActionPerformed(evt);
            }
        });
        jmCapturar.add(jmCBD);

        jMenuBar1.add(jmCapturar);

        jmDispositivos.setText("Dispositivos");
        jMenuBar1.add(jmDispositivos);

        jmOtros.setText("Otros");

        jmSalir.setText("Salir");
        jmOtros.add(jmSalir);

        jmAcerca.setText("Acerca");
        jmOtros.add(jmAcerca);

        jMenuBar1.add(jmOtros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRectTranslucidoComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucidoComplete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtLegajoActionPerformed

private void jmCArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCArchivoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jmCArchivoActionPerformed

private void cmbElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElegirActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbElegirActionPerformed

private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
   // validar el empleado
   EmpleadoDao empleados = new EmpleadoDaoImp();
   List<Empleado> lisaEmpleado = empleados.listarEmpleado();
   boolean encontrado = false;
   Empleado e = null ;
   for ( Empleado empleado : lisaEmpleado) {
       if (empleado.getLegajo()==Integer.parseInt(txtLegajo.getText())) {
           encontrado = true;
           e =empleado;
           break;
       }
   } 
       if (encontrado) {
          // mostrar en el labelEmpleado su nombre 
           lblEmpleado.setText("Bienvenido : "+e.getNombre()); 
          // capturo la imagen y la muestro en el lbl
          Image img =  miPlayer.capturaFoto(this.getPlayer());
          Icon iconoAdaptado= new ImageIcon(img.getScaledInstance(lbllFotoUser.getWidth(),lbllFotoUser.getHeight(),Image.SCALE_DEFAULT)); 
          lbllFotoUser.setIcon(iconoAdaptado);//  si manda en pantalla
          // hay que convertir la imagen a byte[] por medio de un puente 
          // crear la imagen en src y de ahi lo paso a  archivo y luego a byte
          miPlayer.guardaImagenEnFichero(img, new File("src/imagTester"));
          // capturo la imagen guardada en el src y lo llevo a la bd
          File file = new File("src/imagTester");
          byte[] imgByte = new byte[(int) file.length()];
           try {
	        FileInputStream fileInputStream = new FileInputStream(file);
	        //convert file into array of bytes
	        fileInputStream.read(imgByte);
	        fileInputStream.close();
        } catch (Exception ex) {
	        ex.printStackTrace();
        }
           
           String elegir = (String)cmbElegir.getSelectedItem();
          // creoo un objeto asistencia
           Asistencia asistencia =  new Asistencia(elegir,imgByte ,new Date(), new Date());
           asistencia.setEmpleado(e);
           //agrego en la bd
           AsistenciaDao asistencias = new AsistenciaDaoImp();
           asistencias.addAsistencia(asistencia);
          
            
        // muestro en la tabla las asistencias  
        
         Set<Asistencia> conjuntoAsistencia =empleados.getEmpleado(e.getIdEmpleado()).getAsistencias();
        // es necesario hacer esto para que me ordene por idAssitencia
         conjunto = new TreeSet<Asistencia>(new OrdenarAsistenciaPorId());
         conjunto.addAll(conjuntoAsistencia);
         
         TablaUtil.prepararTablaAsambleas(modelo, tablaAsistencia); 
         TablaUtil.cargarModeloAsistencia(modelo,conjunto , tablaAsistencia);
         
         }else{
           JOptionPane.showMessageDialog(this, "Error de validacion , ingrese de nuevo sus datos","Error",JOptionPane.ERROR_MESSAGE);
           txtLegajo.setText("");
           txtClave.setText("");
           cmbElegir.setSelectedItem("Elegir");
       }
    
}//GEN-LAST:event_btnMarcarActionPerformed

private void jmCBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCBDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jmCBDActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    
    ReporteAsitenciaJRDataSource dataSource = new ReporteAsitenciaJRDataSource();
   
    try {
            
            for (Iterator<Asistencia> it = conjunto.iterator(); it.hasNext();) {
            
                Asistencia asis = it.next();
                dataSource.addAsistencia(asis);
                
            }
            
            
            
            Map map = new HashMap();
           map.put("joel","joel kapo");
            JasperPrint jPrint;
            JDialog reporte = new JDialog();
            reporte.setSize(900, 700);
            reporte.setLocationRelativeTo(null);
            reporte.setTitle("INFORME");
           //  JasperReport lreporte = (JasperReport) JRLoader.loadObject("reportes/reporteAsistencia.jasper");
          
           // jPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reportes/reporteAsistencia.jasper"),null, new JRBeanCollectionDataSource(listaAs));
           jPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reportes/reporteAsistencia.jasper"),null, dataSource);
            JRViewer jv = new JRViewer(jPrint);
            reporte.getContentPane().add(jv);
            reporte.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Camara.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Camara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonCircle btnMarcar;
    private org.edisoncor.gui.varios.ClockDigital clockDigital2;
    private org.edisoncor.gui.varios.ClockFace clockFace2;
    private org.edisoncor.gui.comboBox.ComboBoxRound cmbElegir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmAcerca;
    private javax.swing.JMenuItem jmCArchivo;
    private javax.swing.JMenuItem jmCBD;
    private javax.swing.JMenu jmCapturar;
    private javax.swing.JMenu jmDispositivos;
    private javax.swing.JMenu jmOtros;
    private javax.swing.JMenuItem jmSalir;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lbllFotoUser;
    private javax.swing.JPanel panelCam;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelRectTranslucidoComplete panelRectTranslucidoComplete1;
    private javax.swing.JTable tablaAsistencia;
    private org.edisoncor.gui.passwordField.PasswordFieldRectIcon txtClave;
    private org.edisoncor.gui.textField.TextFieldRectIcon txtLegajo;
    // End of variables declaration//GEN-END:variables

}
